
mod 'apt',
  :git    => 'https://github.com/puppetlabs/puppetlabs-apt'

mod 'gcc',
  :git    => 'https://github.com/puppetlabs/puppetlabs-gcc'

mod 'stdlib',
  :git    => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'sensu',
  :git    => 'https://github.com/sensu/sensu-puppet'

mod 'vcsrepo',
  :git    => 'https://github.com/puppetlabs/puppetlabs-vcsrepo'

mod 'rabbitmq',
  :git    => 'https://github.com/puppetlabs/puppetlabs-rabbitmq'

mod 'uchiwa',
  :git    => 'https://github.com/yelp/puppet-uchiwa'

mod 'redis',
  :git    => 'https://github.com/thomasvandoren/puppet-redis'

mod 'staging',
  :git    => 'https://github.com/nanliu/puppet-staging'

mod 'wget',
  :git    => 'https://github.com/maestrodev/puppet-wget'
